apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 194986281052.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 194986281052.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b54b051a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
